### ISSUE TITLE
libsnark (in depends for 1.0.0) fails to build on gcc 4.7.2

### ISSUE THREAD

**Issue by welshjf** [zcash/zcash#1702]
```
g++ -o src/algebra/curves/alt_bn128/alt_bn128_g1.o   src/algebra/curves/alt_bn128/alt_bn128_g1.cpp [...]
In file included from src/common/serialization.tcc:20:0,
                 from src/common/serialization.hpp:102,
                 from src/algebra/fields/bigint.hpp:15,
                 from src/algebra/fields/fp.hpp:13,
                 from src/algebra/curves/alt_bn128/alt_bn128_init.hpp:11,
                 from src/algebra/curves/alt_bn128/alt_bn128_g1.hpp:11,
                 from src/algebra/curves/alt_bn128/alt_bn128_g1.cpp:8:
src/common/assert_except.hpp: In function ‘void assert_except(bool)’:
src/common/assert_except.hpp:8:15: error: ‘runtime_error’ is not a member of ‘std’
compilation terminated due to -Wfatal-errors.
```

Needs to include `<stdexcept>` instead of `<exception>`.

**Comment by joyivan** [comment]
I git the 1.0.3  but I meet the same problem like this " src/common/assert_except.hpp: In function ‘void assert_except(bool)’:
src/common/assert_except.hpp:8:15: error: ‘runtime_error’ is not a member of ‘std’
compilation terminated due to -Wfatal-errors."

**Comment by arcalinea** [comment]
Other users have run into issues building with gcc 4.7.2. Upgrading the compiler fixed it. See #838 for full discussion.

**Comment by arcalinea** [comment]
@joyivan confirmed that updating gcc fixes this issue in #1931 

Closing this issue. For future reference, users should try updating gcc when encountering this error.
