### PR TITLE
depends: Move to Clang 9.0.1

### LINKED ISSUE #4801: Migrate to Clang 9
In #4613 we pinned Clang 8 (which we were already using for macOS builds) as the C++ compiler for all builds. One benefit of this is that both Clang and `rustc` use the LLVM backend, meaning that we can optimise across the Rust/C++ divide. This requires that we use the same LLVM backend version (as LLVM IR is not stable across releases).

This issue can be closed once we are pinning Clang 9.

Known blockers:
- Clang 9 broke compatibility with MinGW 6, which we currently require for Windows builds. MinGW 7 fixes the problem: https://github.com/mirror/mingw-w64/commit/8b2c7826b8d68e2ffc79c286b8792efe4168f666

### PR DESCRIPTION
**Pull request by str4d**
Closes #4801.

Clang 9 status as of 2d74d8273c1675761f0e1dfe542836644fb2878f:
| Platform | Native/Cross | Builds? | Notes |
|---|---|---|---|
| Linux | Native | ✔️ |
| macOS | Native | ✔️❔ |
| macOS | Cross | ❌ | Boost: Uses `g++` instead of `clang` (which it pulls from the system), then `libtool: not found` (which system doesn't have) |
| Windows | Cross | ❌ | Fails final link: `lld-link: error: duplicate symbol: _ZTSSt9exception in zcash_cli-bitcoin-cli.o and in libc++abi.a(stdlib_stdexcept.cpp.obj)` etc. |
| aarch64 | Cross | ✔️ |

Clang 10 status (trying it locally, Ubuntu 16.04 reaches EoS in April 2021 so we could jump):
| Platform | Native/Cross | Builds? | Notes |
|---|---|---|---|
| Linux | Native | ✔️ |
| macOS | Native | ❔ |
| macOS | Cross | ❌ | Same Boost problem as with 9 |
| Windows | Cross | ❌ | [1] |
| aarch64 | Cross | ✔️ |

[1]
```
lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at zcash_cli-bitcoin-cli.o
>>> defined at libc++abi.a(stdlib_stdexcept.cpp.obj)
```

Clang 11 status after #4950 (it has Ubuntu 16.04 binaries? cool):
| Platform | Native/Cross | Builds? | Notes |
|---|---|---|---|
| Linux | Native | ✔️ |
| macOS | Native | ❔ |
| macOS | Cross | ✔️ |
| Windows | Cross | ✔️ | Requires `zstd` package. |
| aarch64 | Cross | ✔️ |

### CODE REVIEW

**Comment by rex4539** [comment]
Compiles fine on native macOS and all tests pass.

**Review by rex4539 — CHANGES_REQUESTED** [review]
Wrong branch. Ignore.

**Review by rex4539 — APPROVED** [review]
ACK https://github.com/zcash/zcash/commit/5a45f31b4194fa6c6989b330f5502d3fe5fbaf79 on native macOS.

**Comment by str4d** [comment]
Confirmed that once #4950 merges, we can jump straight to Clang 11 and everything builds on Ubuntu 20.04. So I'm going to close this and open a Clang 11 PR.
